services:

  remote-server:
    build:
      context: ./src/remote-server
      dockerfile: Dockerfile
    image: registry.gotcraft.dev/screener:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    env_file:
      - ./src/remote-server/.env
    restart: unless-stopped

