# logfilename                                      [owner:group]  mode  count  size   when  flags [/pid_file] [sig_num]
/Users/lubomirstankov/Library/Logs/screener.log                   644   5      1024   *     J
/Users/lubomirstankov/Library/Logs/screener.error.log             644   5      1024   *     J
